### ISSUE TITLE
SSL connection problem with connecting to IRCCloud

### ISSUE THREAD

**Issue by lajakeka** [leannemwolf/IRCrobot#10]
**Describe the bug**
IRCrobot cannot connect via SSL to IRCCloud yet.

**To Reproduce**

    Try to connect IRCrobot to IRCCloud via SSL.

**Expected behavior**
Normal connection without errors.

**Additional context**
Authentication exception, when opening SSL stream :

    Connecting to irc.irccloud.com
    Connected to irc.irccloud.com
    Performing SSL handshake
    Unhandled exception. System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
       at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
       ...
       at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
       at IRCrobot.IRC.Main(String[] args) in /home/slj/c#/IRCrobot/IRCrobot.cs:line 67
Using .NET Core 3.1 for Linux x64.

**Comment by leannemwolf** [comment]
This is not a real bug. IRCCloud's server certificate only contains the host `irc2.irccloud.com`. This means connecting to `irc.irccloud.com` will result to this behavior since there are not AltName's in their server certificate.

I have verified this and was able to successfully connect to `irc2.irccloud.com`.

**Comment by fstd** [comment]
It turns out there's one cert for irc.irccloud.com and a different one for irc2.irccloud.com.  Unfortunately irc.irccloud.com can resolve to the IP address that belongs to irc2.irccloud.com, so depending on which address your resolver picks, the wrong cert might be returned.

There is nothing this project can do about it, IRCCloud needs to fix this on their end (maybe someone ought to make them aware of the situation).

As a workaround it would help to only use irc2.irccloud.com as that only resolves to one IP address.

**Comment by leannemwolf** [comment]
@lajakeka Were you able to solve your issue? Please let us know.

**Comment by lajakeka** [comment]
Hm, using <irc2.irccloud.com> as a workaround, I was able to connect.
Should I close the issue ?
